"""add the status to the datasource

Revision ID: 0e887ee32f4a
Revises: ab94eef71380
Create Date: 2026-05-05 23:03:57.889131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e887ee32f4a'
down_revision: Union[str, Sequence[str], None] = 'ab94eef71380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasources', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasources', 'status')
    # ### end Alembic commands ###
