"""add the is otp verified column

Revision ID: 4ff2c6b465ec
Revises: 377706994509
Create Date: 2026-04-19 16:15:02.857227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff2c6b465ec'
down_revision: Union[str, Sequence[str], None] = '377706994509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_otp_verified', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_otp_verified')
    # ### end Alembic commands ###
