"""add the generated_otp

Revision ID: a7e0d6d86602
Revises: 4ff2c6b465ec
Create Date: 2026-04-19 16:49:15.126082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e0d6d86602'
down_revision: Union[str, Sequence[str], None] = '4ff2c6b465ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('generated_otp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'generated_otp')
    # ### end Alembic commands ###
